import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { AlertCircle, ChevronLeft, Pencil, Trash2 } from 'lucide-react'
import { getDeliveryOrder } from '@/api/deliveryOrders'
import { useDeliveryOrders } from '@/hooks/useDeliveryOrders'
import { DeliveryOrderStatusBadge } from '@/components/deliveryOrders/DeliveryOrderStatusBadge'
import ConfirmDialog from '@/components/ui/ConfirmDialog'
import type { DeliveryOrder } from '@/types/deliveryOrder'
import '@/styles/shared.css'; import '@/styles/detail.css'
const fmtDate = (value: string) => new Date(value).toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
export default function DeliveryOrderDetailPage() {
  const { t } = useTranslation(); const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { remove } = useDeliveryOrders(); const [order, setOrder] = useState<DeliveryOrder | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false)
  useEffect(() => { getDeliveryOrder(Number(id)).then(r => setOrder(r.data)).catch(() => setError(t('deliveryOrders.form.notFound'))).finally(() => setLoading(false)) }, [id, t])
  const erase = async () => { if (!order) return; setDeleting(true); const ok = await remove(order.id); setDeleting(false); if (ok) navigate('/delivery-orders') }
  if (loading) return <div style={{ padding: 40, textAlign: 'center' }}>{t('common.loading')}</div>
  if (!order || error) return <div className="page-error"><AlertCircle size={16} /> {error}</div>
  const customer = order.contract.customer
  return <div className="product-detail"><button className="detail-back" onClick={() => navigate('/delivery-orders')}><ChevronLeft size={16} /> {t('deliveryOrders.detail.back')}</button><div className="detail-header"><div><div className="detail-title-row"><h1 className="detail-name">{order.do_no}</h1></div><div className="detail-badges"><DeliveryOrderStatusBadge status={order.status} /></div></div><div className="detail-actions"><button className="btn btn-secondary" onClick={() => navigate(`/delivery-orders/${order.id}/edit`)}><Pencil size={14} /> {t('common.edit')}</button><button className="btn btn-secondary" onClick={() => setConfirm(true)}><Trash2 size={14} /> {t('common.delete')}</button></div></div><div className="detail-summary-grid"><div className="detail-summary-card"><div className="detail-summary-label">{t('deliveryOrders.fields.deliveryDate')}</div><div className="detail-summary-value">{fmtDate(order.delivery_date)}</div></div><div className="detail-summary-card"><div className="detail-summary-label">{t('deliveryOrders.fields.driverName')}</div><div className="detail-summary-value">{order.driver_name}</div></div><div className="detail-summary-card"><div className="detail-summary-label">{t('deliveryOrders.fields.contract')}</div><div className="detail-summary-value">{order.contract.contract_number}</div></div></div><div className="detail-info-grid"><dl className="detail-meta"><dt>{t('deliveryOrders.fields.customer')}</dt><dd>{customer.first_name} {customer.last_name}{customer.company ? ` (${customer.company})` : ''}</dd><dt>{t('deliveryOrders.fields.deliveryAddress')}</dt><dd>{order.delivery_address}</dd></dl>{order.notes && <div className="detail-description"><div className="detail-section-title">{t('common.notes')}</div><p>{order.notes}</p></div>}</div><div className="doc-editor-section" style={{ marginTop: 16 }}><h3 className="doc-editor-section-title">{t('deliveryOrders.fields.checklist')}</h3>{order.checklist_items.length === 0 ? <p className="cell-muted">{t('deliveryOrders.form.noChecklist')}</p> : <div className="table-wrap"><table className="data-table"><thead><tr><th>{t('deliveryOrders.fields.group')}</th><th>{t('deliveryOrders.fields.item')}</th><th>{t('deliveryOrders.fields.result')}</th><th>{t('deliveryOrders.fields.remark')}</th></tr></thead><tbody>{order.checklist_items.map(item => <tr key={item.id}><td>{item.item_group}</td><td>{item.item_name}</td><td>{item.is_passed ? t('deliveryOrders.fields.passed') : t('deliveryOrders.fields.failed')}</td><td>{item.remark || '—'}</td></tr>)}</tbody></table></div>}</div><ConfirmDialog isOpen={confirm} onClose={() => setConfirm(false)} onConfirm={erase} isLoading={deleting} title={t('deliveryOrders.detail.deleteTitle')} message={t('deliveryOrders.detail.deleteMessage', { number: order.do_no })} /></div>
}
