import { useEffect, useState } from 'react'
import { useFieldArray, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { AlertCircle, ChevronLeft, ClipboardCheck, Loader2, Plus, Trash2 } from 'lucide-react'
import { createDeliveryOrder, getDeliveryOrder, updateDeliveryOrder } from '@/api/deliveryOrders'
import { DELIVERY_ORDER_DEFAULTS, deliveryOrderSchema, type DeliveryOrderFormValues } from '@/schemas/deliveryOrderEditorSchema'
import type { DeliveryOrderConversionPrefill, DeliveryOrderStatus, DeliveryOrderType } from '@/types/deliveryOrder'
import { toast } from '@/store/toastStore'
import { getHeaderColorClass } from '@/utils/routeHeaderColor'
import '@/styles/shared.css'; import '@/styles/detail.css'; import '@/components/documents/DocumentEditor.css'

const DEFAULT_CHECKLIST = [{ item_group: 'Exterior', item_name: 'Body condition and forks' }, { item_group: 'Battery', item_name: 'Battery charge and connections' }, { item_group: 'Hydraulics', item_name: 'Hydraulic oil and lift operation' }, { item_group: 'Safety', item_name: 'Horn, lights, brakes and safety devices' }]
const toInputDateTime = (value: string) => value ? new Date(value).toISOString().slice(0, 16) : ''

export default function DeliveryOrderFormPage() {
  const { t } = useTranslation(); const { id } = useParams<{ id: string }>(); const isNew = !id; const navigate = useNavigate(); const location = useLocation(); const prefill = (location.state as { fromContract?: DeliveryOrderConversionPrefill } | null)?.fromContract
  const [isLoading, setLoading] = useState(!isNew); const [isSaving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [doNo, setDoNo] = useState('')
  const { register, control, handleSubmit, reset, formState: { errors } } = useForm<DeliveryOrderFormValues>({ resolver: zodResolver(deliveryOrderSchema), defaultValues: DELIVERY_ORDER_DEFAULTS })
  const { fields, append, remove, replace } = useFieldArray({ control, name: 'checklist_items' })
  useEffect(() => { if (isNew) { if (prefill) reset({ ...DELIVERY_ORDER_DEFAULTS, contract_id: prefill.contract_id, delivery_address: prefill.delivery_address ?? '' }); return } getDeliveryOrder(Number(id)).then(({ data }) => { setDoNo(data.do_no); reset({ contract_id: data.contract.id, order_type: data.order_type, delivery_date: toInputDateTime(data.delivery_date), delivery_address: data.delivery_address, driver_name: data.driver_name, status: data.status, notes: data.notes ?? '', checklist_items: data.checklist_items.map(x => ({ item_group: x.item_group, item_name: x.item_name, is_passed: x.is_passed, remark: x.remark ?? '' })) }) }).catch(() => setError(t('deliveryOrders.form.notFound'))).finally(() => setLoading(false)) }, [id, isNew, prefill, reset, t])
  const submit = handleSubmit(async values => { setSaving(true); try { const payload = { ...values, delivery_date: new Date(values.delivery_date).toISOString(), notes: values.notes || undefined }; const response = isNew ? await createDeliveryOrder(payload) : await updateDeliveryOrder(Number(id), payload); toast.success(t(isNew ? 'deliveryOrders.toast.createSuccess' : 'deliveryOrders.toast.updateSuccess')); navigate(`/delivery-orders/${response.data.id}`, { replace: true }) } catch { toast.error(t(isNew ? 'deliveryOrders.toast.createError' : 'deliveryOrders.toast.updateError')) } finally { setSaving(false) } })
  if (isLoading) return <div style={{ padding: 40, textAlign: 'center' }}>{t('common.loading')}</div>; if (error) return <div className="page-error"><AlertCircle size={16} /> {error}</div>
  return <div><div className={`page-header page-header-banner ${getHeaderColorClass('/delivery-orders')}`}><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><button className="btn btn-ghost" onClick={() => navigate('/delivery-orders')}><ChevronLeft size={16} /></button><h1 className="detail-name" style={{ fontSize: 20 }}>{isNew ? t('deliveryOrders.form.new') : doNo}</h1></div><button className="btn btn-primary" disabled={isSaving} onClick={() => submit()}>{isSaving && <Loader2 size={14} className="spin" />} {t(isNew ? 'deliveryOrders.form.create' : 'deliveryOrders.form.save')}</button></div>
    <form onSubmit={submit} style={{ display: 'grid', gap: 16, marginTop: 16 }}><div className="doc-editor-section"><h3 className="doc-editor-section-title">{t('deliveryOrders.form.details')}</h3>{prefill && isNew && <div className="form-hint">{t('deliveryOrders.form.prefilled', { contract: prefill.contract_number, customer: prefill.customer_name, forklift: prefill.forklift_label ?? '—' })}</div>}<input type="hidden" {...register('contract_id', { valueAsNumber: true })} /><div className="doc-editor-header-grid"><div className="form-group"><label>{t('deliveryOrders.fields.orderType')}</label><select {...register('order_type')}>{(['delivery', 'return'] as DeliveryOrderType[]).map(type => <option key={type} value={type}>{t(`deliveryOrders.orderType.${type}`)}</option>)}</select></div><div className="form-group"><label>{t('deliveryOrders.fields.deliveryDate')} <span className="required">*</span></label><input type="datetime-local" {...register('delivery_date')} />{errors.delivery_date && <span className="field-error">{t('deliveryOrders.validation.required')}</span>}</div><div className="form-group"><label>{t('deliveryOrders.fields.driverName')} <span className="required">*</span></label><input {...register('driver_name')} /></div><div className="form-group"><label>{t('common.status')}</label><select {...register('status')}>{(['pending', 'in_transit', 'delivered', 'cancelled'] as DeliveryOrderStatus[]).map(s => <option key={s} value={s}>{t(`deliveryOrders.status.${s}`)}</option>)}</select></div></div><div className="form-group" style={{ marginTop: 12 }}><label>{t('deliveryOrders.fields.deliveryAddress')} <span className="required">*</span></label><textarea rows={2} {...register('delivery_address')} /></div><div className="form-group"><label>{t('common.notes')}</label><textarea rows={2} {...register('notes')} /></div></div>
      <div className="doc-editor-section"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h3 className="doc-editor-section-title"><ClipboardCheck size={16} /> {t('deliveryOrders.fields.checklist')}</h3><div style={{ display: 'flex', gap: 8 }}><button type="button" className="btn btn-ghost" onClick={() => replace(DEFAULT_CHECKLIST.map(x => ({ ...x, is_passed: true, remark: '' })))}>{t('deliveryOrders.form.loadTemplate')}</button><button type="button" className="btn btn-secondary" onClick={() => append({ item_group: '', item_name: '', is_passed: true, remark: '' })}><Plus size={14} /> {t('deliveryOrders.form.addItem')}</button></div></div>{fields.length === 0 ? <p className="cell-muted">{t('deliveryOrders.form.noChecklist')}</p> : <div className="table-wrap"><table className="data-table"><thead><tr><th>{t('deliveryOrders.fields.group')}</th><th>{t('deliveryOrders.fields.item')}</th><th>{t('deliveryOrders.fields.result')}</th><th>{t('deliveryOrders.fields.remark')}</th><th /></tr></thead><tbody>{fields.map((field, index) => <tr key={field.id}><td><input {...register(`checklist_items.${index}.item_group`)} /></td><td><input {...register(`checklist_items.${index}.item_name`)} /></td><td><label style={{ display: 'flex', gap: 6, alignItems: 'center' }}><input type="checkbox" {...register(`checklist_items.${index}.is_passed`)} /> {t('deliveryOrders.fields.passed')}</label></td><td><input {...register(`checklist_items.${index}.remark`)} /></td><td><button type="button" className="action-btn danger" onClick={() => remove(index)}><Trash2 size={14} /></button></td></tr>)}</tbody></table></div>}</div></form></div>
}
