import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { AlertCircle, ChevronLeft, ChevronRight, FileText, Plus, RefreshCw, Search } from 'lucide-react'
import PageHeader from '@/components/layout/PageHeader'
import { DeliveryOrderStatusBadge, DeliveryOrderTypeBadge } from '@/components/deliveryOrders/DeliveryOrderStatusBadge'
import { useDeliveryOrders } from '@/hooks/useDeliveryOrders'
import type { DeliveryOrderStatus } from '@/types/deliveryOrder'
import '@/styles/shared.css'

const fmtDate = (value: string) => new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })

export default function DeliveryOrderListPage() {
  const { t } = useTranslation(); const navigate = useNavigate(); const { orders, total, pages, page, params, isLoading, isFetching, error, applyParams, refetch } = useDeliveryOrders()
  return <div>
    <PageHeader title={t('deliveryOrders.list.title')} subtitle={t('deliveryOrders.list.totalCount', { count: total })}><div style={{ display: 'flex', gap: 8 }}><button className="btn btn-ghost" onClick={() => refetch()} disabled={isFetching}><RefreshCw size={14} className={isFetching ? 'spin' : ''} /> {t('common.refresh')}</button><button className="btn btn-primary" onClick={() => navigate('/delivery-orders/new')}><Plus size={15} /> {t('deliveryOrders.list.new')}</button></div></PageHeader>
    {error && <div className="page-error"><AlertCircle size={16} /> {error}</div>}
    <div className="toolbar"><div className="search-wrap"><Search size={14} /><input className="search-input" value={params.q ?? ''} placeholder={t('deliveryOrders.list.searchPlaceholder')} onChange={e => applyParams({ q: e.target.value || undefined, page: 1 })} /></div><select className="filter-select" value={params.status ?? ''} onChange={e => applyParams({ status: (e.target.value || undefined) as DeliveryOrderStatus | undefined, page: 1 })}><option value="">{t('deliveryOrders.list.allStatuses')}</option>{(['pending', 'in_transit', 'delivered', 'cancelled'] as DeliveryOrderStatus[]).map(x => <option key={x} value={x}>{t(`deliveryOrders.status.${x}`)}</option>)}</select></div>
    <div className="table-card"><div className="table-wrap"><table className="data-table"><thead><tr><th>{t('deliveryOrders.fields.doNo')}</th><th>{t('deliveryOrders.fields.orderType')}</th><th>{t('common.status')}</th><th>{t('deliveryOrders.fields.customer')}</th><th className="col-hide-sm">{t('deliveryOrders.fields.deliveryDate')}</th><th className="col-hide-sm">{t('deliveryOrders.fields.driverName')}</th></tr></thead><tbody>{isLoading ? Array.from({ length: 6 }).map((_, i) => <tr key={i} className="skeleton-row"><td><div className="skeleton-cell" /></td><td><div className="skeleton-cell" /></td><td><div className="skeleton-cell" /></td><td><div className="skeleton-cell" /></td><td><div className="skeleton-cell" /></td><td><div className="skeleton-cell" /></td></tr>) : orders.length ? orders.map(order => <tr key={order.id} style={{ cursor: 'pointer' }} onClick={() => navigate(`/delivery-orders/${order.id}`)}><td style={{ fontWeight: 600 }}>{order.do_no}</td><td><DeliveryOrderTypeBadge orderType={order.order_type} /></td><td><DeliveryOrderStatusBadge status={order.status} /></td><td className="cell-muted">{order.contract.customer.first_name} {order.contract.customer.last_name}{order.contract.customer.company ? ` (${order.contract.customer.company})` : ''}</td><td className="cell-muted col-hide-sm">{fmtDate(order.delivery_date)}</td><td className="cell-muted col-hide-sm">{order.driver_name}</td></tr>) : <tr><td colSpan={6}><div className="table-empty"><FileText size={36} /><p>{t('deliveryOrders.list.empty')}</p></div></td></tr>}</tbody></table></div>{pages > 1 && <div className="pagination"><span className="pagination-info">{t('deliveryOrders.list.pageOf', { page, pages, total })}</span><div className="pagination-controls"><button className="page-btn" disabled={page === 1} onClick={() => applyParams({ page: page - 1 })}><ChevronLeft size={14} /></button><button className="page-btn" disabled={page === pages} onClick={() => applyParams({ page: page + 1 })}><ChevronRight size={14} /></button></div></div>}</div>
  </div>
}
